### ISSUE TITLE
vboxManage

### ISSUE THREAD

**Issue by metaapple** [newbackjava/cicdkuber#2]
![Image](https://github.com/user-attachments/assets/5b03e4e2-adba-4518-9947-27e1643642f2)

**Comment by newbackjava** [comment]
![Image](https://github.com/user-attachments/assets/cd3332d1-08f4-4c95-992e-545893939fc1)

**id_rsa.pub --> authorized_keys로 복사**
![Image](https://github.com/user-attachments/assets/c1c51f66-93fc-4985-9a9a-31a0e964dcfc)

![Image](https://github.com/user-attachments/assets/e40a7ac1-d80c-4bbe-93e1-bec0332f2b68)

![Image](https://github.com/user-attachments/assets/7771479b-315e-4b14-a3e3-46466065e69a)

![Image](https://github.com/user-attachments/assets/d22c9f32-0d1c-467a-bf58-16b1ed64fa9f)

![Image](https://github.com/user-attachments/assets/5db95172-cb9d-4f34-895f-f2fa3bc0c690)

![Image](https://github.com/user-attachments/assets/3e26fa27-5a57-4649-82b3-6434ff94ba8d)

```
Host ks8-control
  HostName localhost
  Port 25
  User user1
  IdentitiesFile C:\Users\HPE\.ssh\id_rsa

```

**Comment by newbackjava** [comment]
![Image](https://github.com/user-attachments/assets/835ba994-a1ad-4d3a-8940-f33dfc4c0d2e)

**Comment by newbackjava** [comment]
```



root@ks8-control:/home/user1# cat /etc/netplan/50-cloud-init.yaml 

# This file is generated from information provided by the datasource.  Changes
# to it will not persist across an instance reboot.  To disable cloud-init's
# network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
network:
    ethernets:
        enp0s3:
            addresses:
            - 192.168.15.101/24
            nameservers:
                addresses:
                - 168.126.63.1
                search: []
            routes:
            -   to: default
                via: 192.168.15.1
    version: 2

```
